### ISSUE TITLE
Iterating over api results in no images downloaded

### ISSUE THREAD

**Issue by robmarkcole** [Jimut123/jimutmap#16]
**Describe the bug**
I have a pandas dataframe with locations I wish to download tiles for. I am downloading a limited area around each location. However placing in a loop, I find that often no images are downloaded. Deleting the `chromedriver` and retrying can fix the issue, but not always

**To Reproduce**
```python
for index in tqdm(range(len(df))):
    test_lat = df.iloc[index]['lat']
    test_lon = df.iloc[index]['lon']
    extent = 0.01

    min_lat_deg = test_lat - extent
    max_lat_deg = test_lat + extent
    min_lon_deg = test_lon - extent
    max_lon_deg = test_lon + extent

    print(min_lat_deg, max_lat_deg, min_lon_deg, max_lon_deg)

    download_obj = api(
        min_lat_deg = min_lat_deg, # min_lat,
        max_lat_deg = max_lat_deg, # max_lat,
        min_lon_deg = min_lon_deg, # min_lon,
        max_lon_deg = max_lon_deg, # max_lon,
        zoom = 16, # 0 is min, 17 is good
        verbose = False,
        threads_ = 5, 
        container_dir = img_dir
        )

    download_obj.download(getMasks = False)
    time.sleep(2) # wait for download to finish
```

**Expected behavior**
Either an exception is raised if there are no images to download, or some mechanism is available to retry

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: `jimutmap==1.3.9`

**Additional context**

**Comment by Jimut123** [comment]
I probably might have run into this bug before, but ignored it, as I thought it might be a network connection issue. Here is a workable idea to solve the issue, but not sure if it will be efficient. Let’s keep a temporary database for each run containing the IDs and corresponding marker to tile image and corresponding road masks. We need to continue the download until all the markers are marked to 1.

<table>
    <tr> 
        <th> ID </th>
        <th> Road </th>
        <th> Mask </th>
    </tr>

 <tr>
      <td> XXXXX1_YYYYY1 </td>
      <td> 1 </td>
      <td> 1 </td>
  </tr>
 

 <tr>
      <td> XXXXX1_YYYYY2 </td>
      <td> 1 </td>
      <td> 1 </td>
  </tr>

 <tr>
      <td> XXXXX1_YYYYY2 </td>
      <td> 0 </td>
      <td> 0 </td>
  </tr>

 <tr>
      <td> ... </td>
      <td> ... </td>
      <td> ... </td>
  </tr>
</table>

I am not sure if this will provide a suitable solution. It might also happen that some tiles are not downloading at all and we need to do this repeatedly. Please provide suggestions, if you find a better way to mitigate the problem :)

**Comment by Jimut123** [comment]
I am thinking of using retries as it came to my mind in the first glance of the issue. If the issue is regarding block on the IP or authentication, then I am not sure if that will work out or not. I also thought that it might also be an issue with the ```multiprocessing.pool``` library, since in case of overloading of requests, I am assuming Operating System might kill some requests internally. In that case, retries will be our only option :)

**Comment by Jimut123** [comment]
Probably I will try to find a solution by next week. 
Let’s see. 
If you solve this before, then please feel free to share the solution by doing a PR :)

Best,
-Jimut

**Comment by robmarkcole** [comment]
OK today `threads_=1` appears to be OK...

**Comment by Jimut123** [comment]
I think the maximum threads offered by CPU (in my case it is 4) will also work. 

Thanks for pin-pointing the issue, now I am sure it is a thread issue. The only problem with threads=1 is it will be very slow compared to the others, since it is searching deterministically. But increasing the thread over the capacity of hardware may also cause the computer to slow down, like for example in Linux and Windows-based OS, it slows down considerably and may even result in deadlock (hang). 

Retries will again slow down, since we are checking it repeatedly. Looks like I have to use some buffer mechanism, which selectively retries the links by using the database. It will slow down things considerably, but using multiprocessing within retries may solve the issue. I have an exam tomorrow. Let’s see, I hope I will come up with a workable, efficient solution by next week.

**Comment by Jimut123** [comment]
Eventually, I have to use a database, since I have to write the image stitching module sometime. 

This tool was created with the hypothetical idea of converting 2D satellite images to 3D by using GANs and other related unsupervised deep learning stuffs (back in 2019). 

Not sure when I will get time to work on this project for solving that initial purpose :) But I will come up with the solution to the present bug by next week.

**Comment by robmarkcole** [comment]
I'm quite happy to leave it running over a weekend on my Max, so speed is not my main concern. The generated filenames are unique? One suggestion is the download method could return a dictionary of the created files, request etc. This can then be appended to a pandas data frame, inserted to SQLite db etc.

**Comment by Jimut123** [comment]
Hi, it should work now, created a dirty patch, and it will be a bit slow probably.

Be sure to install the latest version using pip
and then try to check the [test.py](https://github.com/Jimut123/jimutmap/blob/master/test.py) file, and update accordingly.

Kindly tell if it works or not.

**Comment by robmarkcole** [comment]
Tried 1.4.0 but issue persists. I set threads=20 and get this nice warning: `Sorry, 20 -- threads unavailable, using maximum CPU threads : 8`

**Comment by Jimut123** [comment]
Could you please tell what is the expected number of files that are to be downloaded...?
And how many of them are actually being downloaded ?

I think in your code, increasing the sleep might fix the issue.

```
for index in tqdm(range(len(df))):
    test_lat = df.iloc[index]['lat']
    test_lon = df.iloc[index]['lon']
    extent = 0.01

    min_lat_deg = test_lat - extent
    max_lat_deg = test_lat + extent
    min_lon_deg = test_lon - extent
    max_lon_deg = test_lon + extent

    print(min_lat_deg, max_lat_deg, min_lon_deg, max_lon_deg)

    download_obj = api(
        min_lat_deg = min_lat_deg, # min_lat,
        max_lat_deg = max_lat_deg, # max_lat,
        min_lon_deg = min_lon_deg, # min_lon,
        max_lon_deg = max_lon_deg, # max_lon,
        zoom = 16, # 0 is min, 17 is good
        verbose = False,
        threads_ = 5, 
        container_dir = img_dir
        )

    download_obj.download(getMasks = False)
    time.sleep(100) # wait for download to finish
```

**Comment by Jimut123** [comment]
I am not sure about this. Sorry I couldn't solve this, I give up. Probably a multiprocessing issue.
How long is it taking to download all the files using threads=1?

**Comment by robmarkcole** [comment]
Using threads=1 I left it overnight and it completed. OK thanks for looking into this, I will consider other ways to parallize if I need to in future. Cheers
